// ======================================================================
// \title  FppConstantsAc.hpp
// \author Generated by fpp-to-cpp
// \brief  hpp file for FPP constants
// ======================================================================

#ifndef Components_LLVMSequencer_FppConstantsAc_HPP
#define Components_LLVMSequencer_FppConstantsAc_HPP

#include "FpConfig.hpp"

namespace Components {

  enum FppConstant_LLVMSequencer_dataSize {
    LLVMSequencer_dataSize = 256
  };

}

#endif
