#!/usr/bin/env bash

# Source - https://stackoverflow.com/questions/59895/how-do-i-get-the-directory-where-a-bash-script-is-located-from-within-the-script#59916
SRC_DIR=$( dirname -- "$( readlink -f -- "$0"; )"; )
echo "${SRC_DIR}"

# has to be more than one argument
if [ "$#" -lt 1 ]; then
    echo "Usage: $0 <filename>"
    exit 0
fi

# loop over every argument and get the LLVM IR, ELF binary, and .text of ELF
for file in $@; do
    filename=$(basename ${file})
    filename_noextension="${file%.*}"
    filename_noextension_bpf="${filename_noextension%.*}"

    if [[ -f "$file" ]]; then
        # echo "${filename} exists"
        echo "${filename_noextension}.o Assembly Code:"
        # echo "${filename_noextension_bpf}"
        ${SRC_DIR}/llvm-project/build/bin/clang -emit-llvm -S ${filename} -O3 -target bpf -mcpu=duotronic -fno-unroll-loops
        ${SRC_DIR}/llvm-project/build/bin/llc -march=bpf -mcpu=duotronic -filetype=obj -o ${filename_noextension}.o -O0 --print-after-isel -bpf-stack-size=10000 ${filename_noextension}.ll
        ${SRC_DIR}/llvm-project/build/bin/llvm-objcopy -O binary --only-section=.text ${filename_noextension}.o ${filename_noextension_bpf}.o
    else
        echo "Error: $filename: No such file" >&2
    fi
done

exit 0