set(CMAKE_SYSTEM_PROCESSOR riscv64)

set(CMAKE_LINKER_TYPE LLD)

set(CMAKE_C_COMPILER clang)
set(CMAKE_CXX_COMPILER clang++)

set(CMAKE_AR llvm-ar)
set(CMAKE_NM llvm-nm)
set(CMAKE_RANLIB llvm-ranlib)

set(CMAKE_FIND_ROOT_PATH "${CMAKE_CURRENT_LIST_DIR}/riscv")
set(TOOLCHAIN "${CMAKE_CURRENT_LIST_DIR}/riscv")
set(CMAKE_SYSROOT "${TOOLCHAIN}/sysroot")

set(CMAKE_C_COMPILER_TARGET riscv64-linux-gnu)
set(CMAKE_CXX_COMPILER_TARGET riscv64-linux-gnu)

set(CMAKE_C_COMPILER_EXTERNAL_TOOLCHAIN "${TOOLCHAIN}")
set(CMAKE_CXX_COMPILER_EXTERNAL_TOOLCHAIN "${TOOLCHAIN}")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

#set(LLVM_DIR "${CMAKE_CURRENT_LIST_DIR}/llvm-project/build/lib/cmake/llvm")

add_link_options(
	-fuse-ld=lld
)
